"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 20:18:54.117036
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_branch',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('branch_type', sa.String(length=50), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_branch')),
    sa.UniqueConstraint('code', name=op.f('uq_dim_branch_code'))
    )
    op.create_table('dim_category',
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['dim_category.id'], name=op.f('fk_dim_category_parent_id_dim_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_category')),
    sa.UniqueConstraint('code', name=op.f('uq_dim_category_code')),
    sa.UniqueConstraint('parent_id', 'name', name=op.f('uq_dim_category_parent_id'))
    )
    op.create_table('dim_cost_center',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_cost_center')),
    sa.UniqueConstraint('code', name=op.f('uq_dim_cost_center_code'))
    )
    op.create_table('dim_period',
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('period', name=op.f('pk_dim_period'))
    )
    op.create_table('entity_alias',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('alias_raw', sa.String(length=400), nullable=False),
    sa.Column('alias_norm', sa.String(length=400), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_alias')),
    sa.UniqueConstraint('entity_type', 'alias_norm', name='uq_entity_alias_type_norm')
    )
    op.create_index('ix_entity_alias_entity', 'entity_alias', ['entity_type', 'entity_id'], unique=False)
    op.create_table('report_module',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_module'))
    )
    op.create_table('saved_report',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_report'))
    )
    op.create_table('dim_asset',
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_dim_asset_branch_id_dim_branch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_asset')),
    sa.UniqueConstraint('asset_type', 'code', name=op.f('uq_dim_asset_asset_type'))
    )
    op.create_table('dim_item',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], name=op.f('fk_dim_item_category_id_dim_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_item')),
    sa.UniqueConstraint('sku', name=op.f('uq_dim_item_sku'))
    )
    op.create_table('dim_supplier',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_ar', sa.String(length=300), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('primary_category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_category_id'], ['dim_category.id'], name=op.f('fk_dim_supplier_primary_category_id_dim_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_supplier')),
    sa.UniqueConstraint('code', name=op.f('uq_dim_supplier_code'))
    )
    op.create_table('insight',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('dimension', sa.String(length=20), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('estimated_impact', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_insight_module_id_report_module')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_insight_period_dim_period')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight'))
    )
    op.create_index('ix_insight_module_period', 'insight', ['module_id', 'period'], unique=False)
    op.create_table('kpi_value',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('kpi_code', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('prior_period_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('prior_year_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('budget_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_kpi_value_module_id_report_module')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_kpi_value_period_dim_period')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_value'))
    )
    op.create_index('ix_kpi_value_lookup', 'kpi_value', ['module_id', 'kpi_code', 'period'], unique=False)
    op.create_index('uq_kpi_value_key', 'kpi_value', ['module_id', 'kpi_code', 'period', 'dimension', 'dimension_id'], unique=True)
    op.create_table('mapping_template',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('header_signature', sa.String(length=64), nullable=False),
    sa.Column('column_map', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_mapping_template_module_id_report_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_template')),
    sa.UniqueConstraint('module_id', 'name', name=op.f('uq_mapping_template_module_id'))
    )
    op.create_table('report_run',
    sa.Column('saved_report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('output_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['saved_report_id'], ['saved_report.id'], name=op.f('fk_report_run_saved_report_id_saved_report')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_run'))
    )
    op.create_table('import_batch',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('sheet_name', sa.String(length=200), nullable=True),
    sa.Column('mapping_template_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_valid', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mapping_template_id'], ['mapping_template.id'], name=op.f('fk_import_batch_mapping_template_id_mapping_template')),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_import_batch_module_id_report_module')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch')),
    sa.UniqueConstraint('module_id', 'file_hash', name='uq_import_batch_module_file')
    )
    op.create_index('ix_import_batch_module_period', 'import_batch', ['module_id', 'period_from'], unique=False)
    op.create_table('raw_row',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sheet_name', sa.String(length=200), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cleaned', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_raw_row_batch_id_import_batch'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_row'))
    )
    op.create_index('ix_raw_row_batch_row', 'raw_row', ['batch_id', 'row_number'], unique=False)
    op.create_table('fact_budget',
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_fact_budget_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_fact_budget_branch_id_dim_branch')),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], name=op.f('fk_fact_budget_category_id_dim_category')),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_fact_budget_module_id_report_module')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_fact_budget_period_dim_period')),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_fact_budget_raw_row_id_raw_row'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_budget'))
    )
    op.create_index('ix_fact_budget_period_branch', 'fact_budget', ['period', 'branch_id'], unique=False)
    op.create_table('fact_cost',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cost_center_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['dim_asset.id'], name=op.f('fk_fact_cost_asset_id_dim_asset')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_fact_cost_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_fact_cost_branch_id_dim_branch')),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], name=op.f('fk_fact_cost_category_id_dim_category')),
    sa.ForeignKeyConstraint(['cost_center_id'], ['dim_cost_center.id'], name=op.f('fk_fact_cost_cost_center_id_dim_cost_center')),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_fact_cost_module_id_report_module')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_fact_cost_period_dim_period')),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_fact_cost_raw_row_id_raw_row'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['dim_supplier.id'], name=op.f('fk_fact_cost_supplier_id_dim_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_cost'))
    )
    op.create_index('ix_fact_cost_branch_period', 'fact_cost', ['branch_id', 'period'], unique=False)
    op.create_index('ix_fact_cost_module_period', 'fact_cost', ['module_id', 'period'], unique=False)
    op.create_index('ix_fact_cost_supplier_period', 'fact_cost', ['supplier_id', 'period'], unique=False)
    op.create_table('fact_po_line',
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_fact_po_line_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_fact_po_line_branch_id_dim_branch')),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], name=op.f('fk_fact_po_line_category_id_dim_category')),
    sa.ForeignKeyConstraint(['item_id'], ['dim_item.id'], name=op.f('fk_fact_po_line_item_id_dim_item')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_fact_po_line_period_dim_period')),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_fact_po_line_raw_row_id_raw_row'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['dim_supplier.id'], name=op.f('fk_fact_po_line_supplier_id_dim_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_po_line'))
    )
    op.create_index('ix_fact_po_line_item_date', 'fact_po_line', ['item_id', 'po_date'], unique=False)
    op.create_index('ix_fact_po_line_po', 'fact_po_line', ['po_number', 'line_number'], unique=False)
    op.create_table('fact_usage',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['dim_asset.id'], name=op.f('fk_fact_usage_asset_id_dim_asset')),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_fact_usage_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_fact_usage_branch_id_dim_branch')),
    sa.ForeignKeyConstraint(['module_id'], ['report_module.id'], name=op.f('fk_fact_usage_module_id_report_module')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_fact_usage_period_dim_period')),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_fact_usage_raw_row_id_raw_row'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_usage'))
    )
    op.create_index('ix_fact_usage_branch_period', 'fact_usage', ['branch_id', 'period'], unique=False)
    op.create_index('ix_fact_usage_module_metric_period', 'fact_usage', ['module_id', 'metric_code', 'period'], unique=False)
    op.create_table('validation_issue',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_validation_issue_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_validation_issue_raw_row_id_raw_row'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issue'))
    )
    op.create_index('ix_validation_issue_batch', 'validation_issue', ['batch_id', 'severity'], unique=False)
    op.create_table('fact_savings',
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('po_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('savings_type', sa.String(length=30), nullable=False),
    sa.Column('baseline_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('savings_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attrs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raw_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], name=op.f('fk_fact_savings_batch_id_import_batch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['dim_category.id'], name=op.f('fk_fact_savings_category_id_dim_category')),
    sa.ForeignKeyConstraint(['item_id'], ['dim_item.id'], name=op.f('fk_fact_savings_item_id_dim_item')),
    sa.ForeignKeyConstraint(['period'], ['dim_period.period'], name=op.f('fk_fact_savings_period_dim_period')),
    sa.ForeignKeyConstraint(['po_line_id'], ['fact_po_line.id'], name=op.f('fk_fact_savings_po_line_id_fact_po_line')),
    sa.ForeignKeyConstraint(['raw_row_id'], ['raw_row.id'], name=op.f('fk_fact_savings_raw_row_id_raw_row'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['dim_supplier.id'], name=op.f('fk_fact_savings_supplier_id_dim_supplier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_savings'))
    )
    op.create_index('ix_fact_savings_period', 'fact_savings', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_savings_period', table_name='fact_savings')
    op.drop_table('fact_savings')
    op.drop_index('ix_validation_issue_batch', table_name='validation_issue')
    op.drop_table('validation_issue')
    op.drop_index('ix_fact_usage_module_metric_period', table_name='fact_usage')
    op.drop_index('ix_fact_usage_branch_period', table_name='fact_usage')
    op.drop_table('fact_usage')
    op.drop_index('ix_fact_po_line_po', table_name='fact_po_line')
    op.drop_index('ix_fact_po_line_item_date', table_name='fact_po_line')
    op.drop_table('fact_po_line')
    op.drop_index('ix_fact_cost_supplier_period', table_name='fact_cost')
    op.drop_index('ix_fact_cost_module_period', table_name='fact_cost')
    op.drop_index('ix_fact_cost_branch_period', table_name='fact_cost')
    op.drop_table('fact_cost')
    op.drop_index('ix_fact_budget_period_branch', table_name='fact_budget')
    op.drop_table('fact_budget')
    op.drop_index('ix_raw_row_batch_row', table_name='raw_row')
    op.drop_table('raw_row')
    op.drop_index('ix_import_batch_module_period', table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_table('report_run')
    op.drop_table('mapping_template')
    op.drop_index('uq_kpi_value_key', table_name='kpi_value')
    op.drop_index('ix_kpi_value_lookup', table_name='kpi_value')
    op.drop_table('kpi_value')
    op.drop_index('ix_insight_module_period', table_name='insight')
    op.drop_table('insight')
    op.drop_table('dim_supplier')
    op.drop_table('dim_item')
    op.drop_table('dim_asset')
    op.drop_table('saved_report')
    op.drop_table('report_module')
    op.drop_index('ix_entity_alias_entity', table_name='entity_alias')
    op.drop_table('entity_alias')
    op.drop_table('dim_period')
    op.drop_table('dim_cost_center')
    op.drop_table('dim_category')
    op.drop_table('dim_branch')
    # ### end Alembic commands ###
