"""copier analytics: cycles machines invoices evidence

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03 08:02:47.247214
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cycle',
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_cycle')),
    sa.UniqueConstraint('module_id', 'period_year', 'period_month', name='uq_analysis_cycle_period')
    )
    op.create_table('copier_evidence',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('counter_value', sa.Integer(), nullable=True),
    sa.Column('counter_raw', sa.String(length=40), nullable=True),
    sa.Column('printed_at_text', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('matched_machine_ref', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['analysis_dataset.id'], name=op.f('fk_copier_evidence_dataset_id_analysis_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copier_evidence'))
    )
    op.create_table('copier_invoice',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('internal_no', sa.String(length=40), nullable=True),
    sa.Column('electronic_id', sa.String(length=60), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('seller_reg', sa.String(length=40), nullable=True),
    sa.Column('buyer_reg', sa.String(length=40), nullable=True),
    sa.Column('seller_name', sa.String(length=300), nullable=True),
    sa.Column('buyer_name', sa.String(length=300), nullable=True),
    sa.Column('totals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['analysis_dataset.id'], name=op.f('fk_copier_invoice_dataset_id_analysis_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copier_invoice')),
    sa.UniqueConstraint('dataset_id', name=op.f('uq_copier_invoice_dataset_id'))
    )
    op.create_table('copier_machine',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('class_key', sa.String(length=40), nullable=False),
    sa.Column('package', sa.Integer(), nullable=True),
    sa.Column('branch_source', sa.String(length=300), nullable=False),
    sa.Column('branch_display', sa.String(length=300), nullable=False),
    sa.Column('branch_key', sa.String(length=300), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('prev_reading', sa.Integer(), nullable=True),
    sa.Column('cur_reading', sa.Integer(), nullable=True),
    sa.Column('consumption', sa.Integer(), nullable=True),
    sa.Column('excess_stated', sa.Integer(), nullable=True),
    sa.Column('location_group', sa.String(length=120), nullable=True),
    sa.Column('group_kind', sa.String(length=20), nullable=True),
    sa.Column('rent_detail', sa.Integer(), nullable=True),
    sa.Column('detail_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['dim_branch.id'], name=op.f('fk_copier_machine_branch_id_dim_branch')),
    sa.ForeignKeyConstraint(['dataset_id'], ['analysis_dataset.id'], name=op.f('fk_copier_machine_dataset_id_analysis_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copier_machine'))
    )
    op.create_index('ix_copier_machine_dataset', 'copier_machine', ['dataset_id'], unique=False)
    op.create_table('copier_invoice_line',
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('packages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('color', sa.Boolean(), nullable=False),
    sa.Column('a3', sa.Boolean(), nullable=False),
    sa.Column('printers', sa.Boolean(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('sales_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('net_total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('vat_value', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('wht_value', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('wht_rate', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['copier_invoice.id'], name=op.f('fk_copier_invoice_line_invoice_id_copier_invoice'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copier_invoice_line'))
    )
    op.add_column('analysis_dataset', sa.Column('cycle_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True))
    op.add_column('analysis_dataset', sa.Column('role', sa.String(length=24), nullable=True))
    op.add_column('analysis_dataset', sa.Column('status', sa.String(length=12), server_default='ready', nullable=False))
    op.create_foreign_key(op.f('fk_analysis_dataset_cycle_id_analysis_cycle'), 'analysis_dataset', 'analysis_cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_dataset_cycle_id_analysis_cycle'), 'analysis_dataset', type_='foreignkey')
    op.drop_column('analysis_dataset', 'status')
    op.drop_column('analysis_dataset', 'role')
    op.drop_column('analysis_dataset', 'cycle_id')
    op.drop_table('copier_invoice_line')
    op.drop_index('ix_copier_machine_dataset', table_name='copier_machine')
    op.drop_table('copier_machine')
    op.drop_table('copier_invoice')
    op.drop_table('copier_evidence')
    op.drop_table('analysis_cycle')
    # ### end Alembic commands ###
