"""copier paper distribution rows

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-03 19:43:28.767696
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copier_paper_row',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('cartons', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('branch_source', sa.String(length=300), nullable=False),
    sa.Column('branch_display', sa.String(length=300), nullable=False),
    sa.Column('branch_key', sa.String(length=300), nullable=False),
    sa.Column('is_head_office', sa.Boolean(), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('distributed_on', sa.Date(), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['analysis_dataset.id'], name=op.f('fk_copier_paper_row_dataset_id_analysis_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_copier_paper_row'))
    )
    op.create_index('ix_copier_paper_row_dataset', 'copier_paper_row', ['dataset_id', 'distributed_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_copier_paper_row_dataset', table_name='copier_paper_row')
    op.drop_table('copier_paper_row')
    # ### end Alembic commands ###
