"""aramex invoices and shipments

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-03 20:20:25.751406
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aramex_invoice',
    sa.Column('bill_doc', sa.String(length=40), nullable=False),
    sa.Column('invoice_no', sa.String(length=60), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('customer_no', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('pdf_dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('xlsx_dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pdf_totals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('xlsx_totals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['pdf_dataset_id'], ['analysis_dataset.id'], name=op.f('fk_aramex_invoice_pdf_dataset_id_analysis_dataset'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['xlsx_dataset_id'], ['analysis_dataset.id'], name=op.f('fk_aramex_invoice_xlsx_dataset_id_analysis_dataset'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aramex_invoice')),
    sa.UniqueConstraint('bill_doc', name=op.f('uq_aramex_invoice_bill_doc'))
    )
    op.create_table('aramex_shipment',
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('awb', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('pickup_on', sa.Date(), nullable=True),
    sa.Column('route_text', sa.String(length=300), nullable=True),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('product', sa.String(length=12), nullable=True),
    sa.Column('pcs', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('actual_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('base', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('shipper_name', sa.String(length=300), nullable=True),
    sa.Column('sent_by', sa.String(length=300), nullable=True),
    sa.Column('consignee_name', sa.String(length=300), nullable=True),
    sa.Column('attention', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['aramex_invoice.id'], name=op.f('fk_aramex_shipment_invoice_id_aramex_invoice'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aramex_shipment')),
    sa.UniqueConstraint('invoice_id', 'source', 'awb', name='uq_aramex_shipment_source')
    )
    op.create_index('ix_aramex_shipment_invoice', 'aramex_shipment', ['invoice_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aramex_shipment_invoice', table_name='aramex_shipment')
    op.drop_table('aramex_shipment')
    op.drop_table('aramex_invoice')
    # ### end Alembic commands ###
