"""custody advance register

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-03 20:53:20.918935
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_advance',
    sa.Column('dataset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_ref', sa.String(length=80), nullable=False),
    sa.Column('holder_text', sa.String(length=300), nullable=True),
    sa.Column('branch_label', sa.String(length=300), nullable=True),
    sa.Column('branch_kind', sa.String(length=20), nullable=True),
    sa.Column('branch_key', sa.String(length=300), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('advance_on', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('settlement_text', sa.Text(), nullable=True),
    sa.Column('settled_on', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['analysis_dataset.id'], name=op.f('fk_custody_advance_dataset_id_analysis_dataset'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custody_advance'))
    )
    op.create_index('ix_custody_advance_dataset', 'custody_advance', ['dataset_id', 'advance_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custody_advance_dataset', table_name='custody_advance')
    op.drop_table('custody_advance')
    # ### end Alembic commands ###
