"""reference library and asset register

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-03 21:13:02.656785
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_source',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('series_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('as_of_source', sa.String(length=16), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('file_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='ready', nullable=False),
    sa.Column('rows_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contains_personal_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['document_file.id'], name=op.f('fk_reference_source_file_id_document_file')),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_job.id'], name=op.f('fk_reference_source_job_id_extraction_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_source')),
    sa.UniqueConstraint('kind', 'file_hash', name='uq_reference_source_file')
    )
    op.create_index('ix_reference_source_series', 'reference_source', ['series_key', 'version_no'], unique=False)
    op.create_table('asset_register_row',
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('asset_book', sa.String(length=100), nullable=True),
    sa.Column('asset_number', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tag_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location_text', sa.String(length=300), nullable=True),
    sa.Column('location_governorate', sa.String(length=120), nullable=True),
    sa.Column('location_city', sa.String(length=120), nullable=True),
    sa.Column('location_office', sa.String(length=120), nullable=True),
    sa.Column('major_category', sa.String(length=120), nullable=True),
    sa.Column('category_segment', sa.String(length=120), nullable=True),
    sa.Column('accounting_date', sa.Date(), nullable=True),
    sa.Column('in_service_date', sa.Date(), nullable=True),
    sa.Column('in_service_raw', sa.String(length=40), nullable=True),
    sa.Column('prorate_date', sa.Date(), nullable=True),
    sa.Column('prorate_convention', sa.String(length=40), nullable=True),
    sa.Column('deprn_start_date', sa.Date(), nullable=True),
    sa.Column('date_retired', sa.Date(), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=True),
    sa.Column('method_code', sa.String(length=40), nullable=True),
    sa.Column('life_raw', sa.String(length=40), nullable=True),
    sa.Column('current_units', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_period', sa.Date(), nullable=True),
    sa.Column('original_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjusted_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recoverable_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ytd_depreciation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_book_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_depreciation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['reference_source.id'], name=op.f('fk_asset_register_row_source_id_reference_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_register_row'))
    )
    op.create_index('ix_asset_register_row_loc', 'asset_register_row', ['source_id', 'location_text'], unique=False)
    op.create_index('ix_asset_register_row_source', 'asset_register_row', ['source_id', 'asset_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_register_row_source', table_name='asset_register_row')
    op.drop_index('ix_asset_register_row_loc', table_name='asset_register_row')
    op.drop_table('asset_register_row')
    op.drop_index('ix_reference_source_series', table_name='reference_source')
    op.drop_table('reference_source')
    # ### end Alembic commands ###
